schema: http://172.16.10.101:4000/graphql
#schema: http://localhost:4000/graphql
#schema: http://sample.ace-mc-bohol.com:4000/graphql
documents: ./src/framework/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__